### ISSUE TITLE
Detect some popular SSGs and automatically adjust default path(s) accordingly

### ISSUE THREAD

**Issue by jakejarvis** [jakejarvis/netlify-plugin-cache#2]
Expands on #1.

Could pull some of the logic from https://github.com/netlify/cli/tree/master/src/detectors

**Comment by ehmicky** [comment]
I personally think it might be best to keep this plugin generic.

When it comes to library/third-party/SSG specific cache, Netlify already tries to perform this, regardless of Build plugins, as part of the [`build-image`](https://github.com/netlify/build-image). For example [here](https://github.com/netlify/build-image/blob/c23500190e408b04bdfcf9703d16c460ef03b813/run-build-functions.sh#L675). It would be more useful to send PRs to the `build-image` to add more logic there than to augment this plugin IMHO.

However, caching logic that targets only one library/third-party/SSG are perfect candidates for individual, separate Build plugins! I think mixing it with the generic approach of this plugin might decrease its simplicity.

**Comment by jakejarvis** [comment]
Completely agree, the simpler the better. Good to know how much the build image already does. Between that and the existing more specific plugins I'll keep this generic as advertised. 👍
