### ISSUE TITLE
"Unable to deserialize cloned data" error

### ISSUE THREAD

**Issue by Rarst** [jakejarvis/netlify-plugin-cache#28]
Trying to cache Playwright's Chromium dependency (it seems to go into `.cache` so not customizing defaults path) and plugin breaks the build with the following:

> 2:34:48 PM: ❯ Loading plugins
> 2:34:48 PM:    - netlify-plugin-cache@1.0.3 from netlify.toml and package.json
> 2:34:49 PM: Uncaught exception, the process will now terminate…
> 2:34:49 PM: Error: Unable to deserialize cloned data due to invalid or unsupported version.
> 2:34:49 PM:     at parseChannelMessages (node:internal/child_process/serialization:72:20)
> 2:34:49 PM:     at parseChannelMessages.next (<anonymous>)
> 2:34:49 PM:     at Pipe.channel.onread (node:internal/child_process:611:18)

Re-running build with cache cleared doesn't help.

**Comment by hrishikesh-k** [comment]
This can be closed. It's an issue with Netlify not handling Node version 18 correctly, and not the plugin.

Officially answered here: https://answers.netlify.com/t/71151
